gerwazy – gerwazy
gerwazy Program
45 statements
Source File
Uses:
readline_module
parse_module
welcome_module
Calls
Variables
lun success line ask bid askV bidV FILEN LNSIZE KERNEL STR ET
Variables
Type Attributes Name Initial
integer :: lun
logical :: success
character(len=:), allocatable :: line
character(len=7) :: ask
character(len=7) :: bid
character(len=7) :: askV
character(len=7) :: bidV
integer, parameter :: FILEN = 128
integer, parameter :: LNSIZE = 60
character(len=F) :: KERNEL
character(len=L) :: STR
double precision :: ET
All Programs
gerwazy mode_high_low
Call graph
gerwazy calls welcome, str2et, furnsh, readline
welcome calls count_lines