mode_high_low – gerwazy
mode_high_low Program
55 statements
Source File
Uses:
readline_module
welcome_module
REAL_VECTORS
mode_module
Calls
Variables
v_tick tick size lun success line FILEN LNSIZE KERNEL STR ET time start_time tick_time volume sigma_volume
Variables
Type Attributes Name Initial
type(VECTOR) :: v_tick
type(VECTOR_DATA) :: tick
integer :: size
integer :: lun
logical :: success
character(len=:), allocatable :: line
integer, parameter :: FILEN = 128
integer, parameter :: LNSIZE = 60
character(len=F) :: KERNEL
character(len=L) :: STR
double precision :: ET
integer :: time
integer :: start_time
integer :: tick_time
real(kind=8) :: volume
real(kind=8) :: sigma_volume
All Programs
gerwazy mode_high_low
Call graph
mode_high_low calls welcome, str2et, vector_create, readline, vector_append, vector_delete_elements, vector_size, furnsh, stat_mode
welcome calls count_lines
vector_create calls vector_destroy
vector_append calls vector_increase_capacity
stat_mode calls qsort_reals
qsort_reals calls qsort_reals